Use _NIOFileSystem for file system operations.
swiftlang/swift-sdk-generator pull request #137
Opened 2024-09-30 01:07 UTC by zaneenders

Motivation:
Add support for _NIOFileSystem to move away from OSFileSystem as per issue #76.

Modifications:
Add SDKFileSystem that uses _NIOFileSystem. Change default AsyncFileSystem to SDKFileSystem

Result:

Using Swift NIO for file system operations.

2024-09-30 06:43 UTC, MaxDesiatov commented
@swift-ci test

2024-09-30 09:05 UTC, MaxDesiatov requested changes

2024-09-30 09:05 UTC, MaxDesiatov commented on Sources/Helpers/Vendor/_AsyncFileSystem/SDKFileSystem.swift
> +    public func withOpenReadableFile<T: Sendable>(
I don't think we should reinvent the wheel here and reimplement `with*` methods from scratch. The main motivation for using `_NIOFileSystem` in the first place is that it already [implements these methods](https://swiftpackageindex.com/apple/swift-nio/2.73.0/documentation/_niofilesystem/filesystem/withfilehandle(forreadingandwritingat:options:execute:)) and provides necessary abstractions, like [`FileSystemProtocol`](https://swiftpackageindex.com/apple/swift-nio/2.73.0/documentation/_niofilesystem/filesystemprotocol).

2024-12-09 20:56 UTC, zaneenders commented
Hey, some personal matters have come up and I don't think I will be able to work on and finish this in a timely matter. I'm sorry for taking so long to notify you.

2024-12-09 20:56 UTC, closed without merging